server:
  port: 8080
spring:
  application:
    name: reggie_take_out
#  redis 连接信息
  redis:
    host: localhost
    port: 6379
    database: 0
#    SpringCache缓存
  cache:
    redis:
      time-to-live: 1800000   # 设置缓存过期时间
  #    MySQL连接信息
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  img-path: D:\\reggie\img\


#sms:
##  templateCode: SMS_154950909
#  endpoint: dysmsapi.aliyuncs.com
#  accessKeyId : LTAI5tAFCGJXq1SSe1cbPBpM
#  accessKeySecret: ZrrfjyTNJYs8yVgzT3tePhUhlJROp0

#阿里云 OSS
#aliyun:
#  oss:
#    file:
#      endpoint: oss-cn-guangzhou.aliyuncs.com
#      keyid: LTAI5tMgrBKer7G3Ad3z7nvR
#      keysecret: 01uJWcl5kZdXxCxHvR9LSbBttLSYi0
#      bucketname: rofox